
        export const data: any = [
  {
    "title": "K.N. Nehru's brother abducted, murdered",
    "content": "K.N. Ramajeyam, younger brother of K.N. Nehru, former Transport Minister and Tiruchi district secretary of Dravida Munnetra Kazhagam, was brutally murdered, apparently after he was abducted by unidentified assailants from the posh Thillai Nagar in the city on Thursday. Ramajeyam, aged 50, was suspected to have been intercepted when he went for his morning walk. He left home around 5.15 a.m. Hours later, his body was found in a bush on the banks of the Cauvery near Thiruvalarsolai, on the outskirts. Police sources said his wife had received a call from Ramajeyam's mobile phone, but the caller disconnected it quickly. His body, spotted by a police patrol team a few hours later, bore severe head injuries. He was found gagged and his hands and legs were tied. Tension prevailed in the Thillai Nagar area and in front of the GH as a large number of party cadres thronged his house and the hospital. Shops and commercial establishments in and around Thillai Nagar put up the shutters. Some schools remained closed for the day. Mr. Nehru, who rushed from Chennai to the hospital, was seen crying inconsolably. Emotions ran high as party cadres damaged signboards and furniture at the hospital mortuary, while a few threw stones at the window panes of a nursing students' hostel. Ramajeyam had been cited an accused and was arrested with Mr. Nehru in two cases of land grab, including the case in which he was charged with forcibly acquiring land for the Kalaignar Arivalayam, the party office in the city. Ramajeyam was into granite export and other businesses. He headed the G. Narayanan Educational Trust, which is running the CARE group of educational institutions in the city. He was also the president of the Tamil Nadu Basketball Association. Though Ramajeyam did not hold any position in the DMK, he was seen as a power centre in the party. Ramajeyam is survived by his wife, son Vineeth and daughter Janani.  Published - March 29, 2012 03:08 pm IST  murder / state politics / Tiruchi "
  },
  {
    "title": "Advocate murdered in Trichy",
    "content": "An advocate was murdered in the city on Monday night. The victim Mathiazhagan was on a walk with his pet dog near Rukmini theatre in Woraiyur area, when he was attacked by armed culprits. The incident that occurred in a small lane, shook the residents of the area. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Police sources said the advocate received a deadly blow with a weapon on his head by the culprits causing his death instantly. Shailesh Kumar Yadav, Commissioner of Police, and senior police officials inspected the crime scene and conducted inquiries. The motive behind the murder is being investigated. A team of five inspectors are on the job of obtaining tangible clues. Forensic experts also inspected the scene of crime. The Woraiyur police are investigating.  Published - May 06, 2014 12:37 pm IST  murder / Tiruchi "
  },
  {
    "title": "Painter found dead near Tiruchi, police suspect murder",
    "content": "A 39-year-old man was found murdered at Vengur on the outskirts of Tiruchi on Tuesday. The body of S. Prabhakaran, a resident of Vengur, was found with multiple wounds at the spot. Prabhakaran was unmarried and had been working as a painter. The motive behind the murder is suspected to be him having an affair with a married woman. Further investigation is on. The Tiruverumbur police are investigating, said the police sources.   Published - February 04, 2025 07:04 pm IST  Tiruchi / murder "
  },
  {
    "title": "History sheeter murdered in Tiruchi, six arrested",
    "content": "A 35-year-old history sheeter was murdered by a gang of armed men at Nandha Nagar near No. 1 Tollgate in Tiruchi district on Saturday morning. The police arrested six persons in connection with the case within hours after the murder.  Police sources identified the deceased as J. Bharanidharan, a native of Mela Kondayampettai at Thiruvanaikoil in Tiruchi. He was classified under the A category of anti-social elements on the list of history-sheeters against whom more than 20 cases, including the charges of robbery and attempt to murder, had been pending at various police stations in Tiruchi, Nagapattinam, and Perambalur districts.  The police said he had been living with his family at Nandha Nagar near No. 1 Tollgate. On Saturday morning, a group of armed men entered his house, assaulted him using weapons, and fled the spot. Bharanidharan died of injuries on the spot.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The Kollidam police shifted his body to the Government Hospital at Srirangam for an autopsy and registered a case under Sections 302 (Punishment for murder), 147 (Punishment for rioting), 148 (Rioting, armed with deadly weapon.), 294 (b) (sings, recites or utters any obscene song, ballad or words, in or near any public place), and 449 (House-trespass in order to commit offence punishable with death) of the Indian Penal Code.  The Tiruchi district police formed special teams to identify and arrest the accused. During the investigation, the police found that he had enmity with P. Sakthivel, 36, a history sheeter who hails from Kuzhumani in Tiruchi.  The police said Bharanidharan reportedly attempted to misbehave with wife of Sakthivel. On knowing this, Sakthivel along with B. Parthiban, 28, M. Dineshkumar, 25, K. Gopalakrishnan, 35, M. Dinesh, 24, and S. Mugilkumar, 30, all natives of Tiruchi, allegedly murdered Bharanidharan in his house.  The police arrested the accused and are investigating the case.   Published - February 03, 2024 08:04 pm IST  Tiruchi / murder / crime / police "
  },
  {
    "title": "History-sheeter murdered near liquor shop in Tiruchi, five arrested",
    "content": "A 47-year-old history-sheeter was beaten to death by a group of persons near a TASMAC liquor shop on Iqbal Colony-Mudukkupatti Road here after an argument over wages on Tuesday. Police have arrested five persons in connection with the murder. Vellaichamy alias Panneerselvam ,47, a resident of Vinayakar Kovil Street in Mudukkupatti, was employed as a plumber by Santhanam, a resident of Edatheru in Palakkarai. On the day of the incident, Vellaichamy and his friend, Raghavendran, were consuming alcohol at the TASMAC shop. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. A dispute over wages broke out between Vellaichamy and Santhanam, who was also present at the shop. Following the argument, Santhanam left the premises and returned with his friends.  When Vellaichamy stepped out of the shop, he was attacked near Iqbal Colony by Santhanam and his associates — Balaji, Srinivasa Perumal, Balamohanraj, Ramkumar, and Gokul from Kuppankulam. They used iron rods and wooden sticks to assault him.  Passers-by rushed the severely injured Vellaichamy to Tiruchi MGMGH, where doctors declared him dead on arrival. Based on a complaint filed by the victim’s brother, Nagaraj, at the Cantonment Police Station, a case was registered. The police arrested Santhanam, Balaji, Srinivasa Perumal, Balamohanraj, and Ramkumar. Efforts are under way to apprehend Gokul, who is absconding.  Published - January 15, 2025 06:25 pm IST"
  },
  {
    "title": "Trichy woman seeks CBI probe into daughter’s death",
    "content": "A 40-year-old woman from Tiruchi has moved the Madras High Court bench here seeking transfer of probe into her 12-year-old-daughter’s death from the Crime Branch-Criminal Investigation Department (CB-CID) to the Central Bureau of Investigation (CBI). In her petition, P. Mahaboo Nissa claimed that her daughter A. Thoufik Sulthana, an eighth standard student, was found dead, with her body parts mutilated, under mysterious circumstances on a railway track in Tiruchi on August 13, 2008. Railway police had registered a case under Section 174 (suspicious death) of Code of Criminal Procedure (CrPc) and the case was transferred to the Edamalaipatti police for investigation. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The family came to know from Ms. Sulthana’s friends that she was followed by two men for two days prior to her death and the police were informed about the persons who had stalked the teenager, but the police failed to inquire the stalkers and take them into custody, she said. According to Ms. Nissa, her daughter could have been raped and murdered elsewhere and body parts scattered on the railway track, because there were no traces of blood near the track. The petitioner also expressed apprehension that Ms. Sulthana could have been killed for human sacrifice. Based on a representation submitted by a social worker, the Director General of Police had transferred the probe to the CB-CID, but to date there was no progress in the investigation, she claimed. The CB-CID sleuths failed to alter the case under Section 302 (murder) of the Indian Penal Code and did not conduct an inquiry to trace the accused, she added. Therefore, she pleaded with the court to transfer the case to the CBI.  Published - December 16, 2013 11:11 am IST  murder / Tiruchi / judiciary (system of justice) "
  },
  {
    "title": "Six surrender in murder case",
    "content": " A day after two brothers were murdered by an armed gang at Koppu on Wednesday, six persons surrendered before the Judicial Magistrate Court at Kumbakonam in Thanjavur district on Thursday. E. Nagaraj (26), the prime accused and belonging to the same village where the victims resided, M. Gopal, T. Manikandan, R. Dinesh, R. Vignesh and P. Elumalai surrendered before the court.  The Jeeyapuram police, which had booked a murder case, named seven accused along with a few others in the murder of G. Raja and Bhoopathy. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Police have planned to take them into custody to interrogate them.  They believe that the murder was a sequel to a previous enmity and vengeance between Nagaraj and the brother duo a few months ago on a petty issue. Nagaraj, who was involved in a murder case in Jeeyapuram police station this year, had come out on bail. Only after taking the accused into police custody and interrogating them would give a clear picture regarding the motive behind the brutal murder. Meanwhile, post mortem was conducted on the two bodies at the Mahatma Gandhi Government Hospital here on Thursday. Thereafter, it was handed over to the near ones of the victims. Police force was deployed at Koppu as a precautionary measure.  Published - November 04, 2016 02:45 am IST"
  },
  {
    "title": "Forensic experts visit BSNL office in Tiruchi to analyse CDR in Kodanad murder case",
    "content": "A team of experts from the National Forensic Sciences University at Gandhi Nagar in Gujarat and officers from the Crime Branch - CID on Friday visited the BSNL office in Tiruchi to examine the Call Detail Record (CDR) tapes related to the Kodanad estate dacoity-cum-murder case.  Police sources said a team of two forensic sciences experts accompanied by seven officers of the CB-CID, which is investigating the dacoity-cum-murder at the estate of former Chief Minister Jayalalithaa at Kodanad in the Nilgiris in 2017, arrived at the BSNL office on West Boulevard Road at Singarathope on Friday afternoon.  The experts and investigation officers visited the BSNL office where CDRs were stored to retrieve data from the magnetic tapes and analyse it from servers for cyber forensic analysis in connection with the case, the police sources added.   Published - February 02, 2024 07:33 pm IST  Tiruchi / Jayalalithaa / murder "
  },
  {
    "title": "Five arrested in history-sheeter’s murder",
    "content": "Five persons were arrested by the police on Wednesday in connection with the murder of a history-sheeter, S.Muthukumkar, in Tiruchi on Tuesday. S. Muthukumar, 32, from Thidir Nagar in Ariyamangalam was murdered on Tuesday by a six-member gang opposite SIT College on the Tiruchi-Thanjavur National Highway. Based on a complaint filed by Muthukumar’s mother Kayalvizhi, the Ariyamangalam police filed a case and arrested P. Loganathan, 30, B. Kumaresan, 25, G. Dinesh, 26, M. Thangamani, 40, and A. Ilanchezhiyan, 24. After being produced before the Judicial Magistrate Court VI the accused were sent to the Tiruchi Central Prison. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Another suspected accused S. Prasad, 24, has absconded and the police were in search of him. Muthukumar’s murder is suspected to be a sequel to a long running feud between his father Sekar and his brother Periyasamy. Both Sekar and Periyasamy were murdered by the rival groups.  Published - May 01, 2024 05:54 pm IST"
  },
  {
    "title": "Four get life term in the murder of ‘Cable’ Sekar",
    "content": "The Second Additional District and Sessions Court here on Monday convicted and sentenced four persons to undergo life imprisonment for murdering ‘Cable’ Sekar, who held the post of AIADMK Golden Rock area secretary, in November 2011. Imposing a fine of Rs. 5,000 each on the four accused – Silambarasan, Vivek, Bala alias Balasubramanian and Pushparaj – the Judge Rahman, however, acquitted five other accused in the case. Husband of AIADMK Councillor Kayalvizhi, who represents ward 29, ‘Cable’ Sekar was hacked to death by an armed gang near his house in Ambikapuram here on November 25. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. He was intercepted and murdered by the gang led by his late elder brother Periasamy’s son Silambarasan, following a dispute over property. The Ariyamangalam police booked a case under IPC sections 302 (murder), 147 (rioting), 148 (rioting armed with deadly weapon), 341 (wrongful restraint), 120 B (conspiracy) and 506 (II) (criminal intimidation) and named 12 persons as accused. One of the accused, Vadivel, died when the trial was on, while another, Zakir Hussain, is reported to be absconding. The case was split with respect to another accused ‘Paambukutti’ Nagendran, since he was reported to be absconding when the trial began. He was arrested by the police subsequently. Hearing in his case has been posted for September 2. Among those acquitted was Parvathi, mother of Silambarasan.  Published - August 27, 2013 02:40 pm IST  crime / murder / Tiruchi / arrest / police "
  },
  {
    "title": "Two arrested in realtor murder case",
    "content": "Somarasampet Police have booked a case against four persons, including DMK Andhanallur union secretary P. Kathirvel and Ravi Murugaiah, chairman, Vasan Estates, in connection with the murder of P. Sivakumar (50) who was involved in real estate business at Sengathirsolai village near Tiruchi on Sunday evening. The case was booked against them on a complaint preferred by Sivakumar's wife S. Mythili (35).  Of the four accused named in the murder case, the Somarasampet Police on Monday arrested N. Prabhakaran (34) and A. Deepak (28). The other two persons named as accused were yet to be arrested, police sources said. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The sources said Malliyampathu panchayat president Vigneswaran had the encroachments in Sengathirsolai cremation ground removed through government officials recently. The action caused problems for Sivakumar as an impression had gained ground that he was instrumental in the removal of encroachments.  Mythili, in her complaint to the Somarasampet Police on Sunday, stated that her husband was attacked with wooden logs by Prabhakaran and Deepak, also from Sengathirsolai village, leading to his death at the instigation of Kathirvel and Ravi Murugaiah and sought action against the four. Based on the complaint, the Somarasampet Police registered a case under IPC sections, including 302 (murder) 109 (abetment), naming Prabhakaran, Deepak, Kathirvel and Ravi Murugaiah as the accused. Meanwhile, relatives of Sivakumar staged a road roko in front of Mahatma Gandhi Memorial Government Hospital here on Monday demanding the arrest of Kathirvel and Ravi Murugaiah. They refused to receive the body of Sivakumar after completion of autopsy at the government hospital.  Published - November 29, 2021 07:30 pm IST"
  },
  {
    "title": "Construction worker murdered in a drunken brawl in Lalgudi",
    "content": "  A 27-year-old construction worker was murdered in a drunken brawl at Kailash Nagar in Lalgudi police station limits late on Monday night.  Police sources have identified the body as that of S. Ajithkumar, 27, from Needamangalam. Ajithkumar and a co-worker P. Sathish, 29, had picked a quarrel while consuming liquor. Sathish allegedly attacked Ajithkumar with a steel rod and was rushed to Lalgudi GH but died on the way.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Sathish was arrested and later remanded in custody, the police said.   Published - December 09, 2024 08:44 pm IST  Tiruchi / murder "
  },
  {
    "title": "Missing man found murdered",
    "content": "Days after he was reported missing, a 35-year-old man was found beheaded here on Thursday. Based on the information given by one of the accused Vijay who surrendered before the Village Administrative Officer, the police found the body of M. Khaja Hussain along the Cauvery river bank at Oyyamari. Police said Khaja Hussain, a resident of Khajamalai and who was running a welding unit, was reported missing on March 21 night and his family lodged a complaint to the K.K. Nagar police station the next day. The police booked a man missing case. Meanwhile, Vijay surrendered before the VAO and informed that he along with five others had murdered Khaja Hussain and dumped the body along the Cauvery river bank. The police detained Vijay for inquiry and a special team has been constituted to apprehend the remaining accused. Police suspect that the murder had been committed due to some issues in land purchase. Sources said more information would come to light after apprehending the remaining accused. The police are investigating. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - March 25, 2016 12:00 am IST"
  },
  {
    "title": "275 students fight to pocket glory at carrom meet in Trichy",
    "content": "Concentration was the watchword for the participants at the district-level carrom tournament that concluded here on Friday. The challenge was in remaining focused and finding the target consistently. The two-day tourney, which was organised by the Tiruchi-unit of Sports Development Authority of Tamil Nadu at Anna Stadium, attracted nearly 275 students from about 35 schools. “Playing carrom helps in improving concentration and would have a positive impact on academic performance of the students,” said P.Kalaiselvan, district sports officer. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The tournament was conducted under two categories – juniors (students up to standard V) and seniors (students of standards VI to XII). Singles and doubles events were held for both boys and girls. R.Senthilkumar, secretary, Tiruchi District Carrom Association, gave away the prizes. The winners Juniors: Boys: Singles: R.Sabari Girinathan (Oxford Nursery and Primary School). Doubles: S.Arockia Astin and A.Martish (Holy Redeemers Middle School). Girls: Singles: S.D. Bhavadharani (Corporation Middle School, Senthaneerpuram). Doubles: S.K.Banu and R.Yazhini (Methodist Nursery and Primary School). Seniors: Boys: Singles: S.Santhosh Kumar (Corporation Higher Secondary School, Keelansalai). Doubles: L.John Joseph and J.Lukas (R.C. Higher Secondary School). Girls: Singles: N.Akilasree (St.Joseph’s Girls Higher Secondary School, Ponmalaipatti). Doubles: P.Vanitha and R.Sabitha (St.Joseph’s Girls Higher Secondary School, Ponmalaipatti).  Published - October 13, 2013 11:56 am IST  Tiruchi / carrom "
  },
  {
    "title": "History sheeter involved in murder of former Puducherry Assembly Speaker nabbed in Tiruchi",
    "content": "A special team of Tiruchi District Rural Police on Wednesday arrested a history sheeter near Tiruverumbur on charges of possessing arms. He was involved in the murder of the former Puducherry Assembly Speaker in 2017. Police sources identified the arrested person as J. Dinesh Kumar alias Bottle Mani, 30, a native of Tiruverumbur, who had been absconding from police for a long time. Several cases, including two cases of murder, have been pending against him. He was classified as an A+ category of anti-socials in the list of history sheeters. On Wednesday, a special team of police arrested him for possessing arms near Tiruverumbur. He was booked under the provisions of the Arms Act and remanded in judicial custody at Tiruchi Central Prison. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Police sources said he was involved in the murder of former Puducherry Assembly Speaker VMC Sivakumar, who was hacked to death by a six-member armed gang at Neravy in Karaikal on January 3, 2017. Further investigations are on.  Published - December 06, 2023 09:26 pm IST"
  },
  {
    "title": "Manachanallur Guna arrested in Tiruchi",
    "content": "A notorious rowdy Guna alias Manachanallur Guna alias Gunaseelan involved in grave offences, including murder and who was on the run, was arrested by a special team of the city police here on Thursday. A country made pistol, six live rounds, a two-wheeler, three cell phones and four SIM cards were recovered by the team from Guna who has been remanded and lodged in the Central Prison here. Involved in 23 cases, including five murders besides robbery and kidnapping, Guna was apprehended by the team during a vehicle check conducted on Tiruchi–Samaypuram Main Road near Mambazha Salai. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The rowdy who came in an unregistered motorcycle pushed a sub-inspector and threatened to kill him by showing the country made pistol. The police team chased Guna and apprehended him, Commissioner of Police Shailesh Kumar Yadav said on Friday. The Srirangam police has registered a case on a complaint from the sub-inspector under different IPC sections and under the Arms Act. Terming Guna as a dangerous element, Mr. Yadav told presspersons here that investigation was on to find out those who had been supporting and harbouring Guna who was involved in “katta panchayat”. The police were on the look out for Guna who was on the run for one year and had been constantly changing his SIM cards, Mr. Yadav said. The police received intelligence information about the rowdy moving with a pistol causing concern that he could breach peace and create insecurity. A couple of days ago, Guna had extorted money from a person by name Prabhakaran at Woraiyur and a case was booked against him in this connection, he said. Five warrants were pending against him — three in city police limits, one in Tiruchi district, and one in Chengalpattu. Noting that Guna’s arrest was a good catch, Mr. Yadav said the timing was right as the rowdy could have been used for settling scores during the election period. The pistol used by Guna was bought from a person in Villupuram, the Commissioner said. Although the pistol was a country made weapon, it had a good calibre and was as good as an original weapon of that kind, he said. Stating that the city police had been going after anti-social elements, he said eight rowdies were arrested in the last one month and sent for remand.  Published - March 22, 2014 12:35 pm IST  gangs & organised crime / Tiruchi / arrest / law enforcement "
  },
  {
    "title": "Brother allegedly kills sibling with mother’s assistance",
    "content": " A man was allegedly murdered by his brother following an argument between the two on Sunday night. Both the accused and his mother, who allegedly helped cover up the crime, were arrested by police on Monday. In the early hours of Monday, locals discovered an auto rickshaw in the Kollidam bridge with the body of a young man with multiple injuries. On being alerted, the Srirangam police sent the body for postmortem. CCTV footages showed that the auto rickshaw belonged to Thameemun Ansari, 33, from Bheema Nagar. Upon investigation, it was revealed that Ansari’s brother, Saiyad Abudahir, 29, was allegedly responsible for the murder. Abudahir was assisted by their mother, Parveen Banu, 48, in the cover-up. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Initially, Abudahir intended to dispose of the body in the Kollidam River. However, due to increased vehicle traffic, he left the body on the bridge instead.  Ansari, struggling with alcohol addiction and marital issues, reportedly had frequent disputes with his family over money for alcohol. The incident occurred on Sunday night when Ansari demanded more money for alcohol from his mother. In a turn of events as Abudahir attacked Ansari with a sickle, striking him on the head. After Ansari fell, Abudahir strangled him with an electric wire. The Srirangam police have filed a case and arrested Saiyad Abudahir and Parveen Banu. Further investigations are underway.  Published - July 22, 2024 07:11 pm IST"
  },
  {
    "title": "Man arrested for killing elderly woman",
    "content": " The Fort Police have cracked a murder case by arresting a man on charges of killing an elderly woman and dumping the body in a gunny sack and throwing it in a garbage bin in Tiruchi. The body of A. Kalyani, 70, of Thiruvasi in Manachanallur block in Tiruchi district was found near the Super Bazaar car parking lot in the city.  The police recovered from the accused M. Abdul Hasan, 54, a couple of ear studs and a nose pin worn by the victim. Abdul Hasan, a native of Kayalpattinam in Thoothukudi district, had been working in a readymade garments shop near the parking lot. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Police sources said Kalyani, a widow, had been residing with her younger brother Nagappan at Thiruvasi village. The woman had been receiving family pension. She left her house on December 8 to Tiruchi and did not return. Her relatives launched a search. Later, on information from locals the Fort Police found the body of the woman in a gunny sack that was tied and thrown in a garbage bin. Police personnel found blood stains on the nose and mouth of the victim’s body and sent it for autopsy. Acting on a complaint preferred by the woman’s son A. Vanathan, 42, working as a pointsman at Valadi railway station near Lalgudi, the Fort Police booked a murder case. It came to light during inquiries and analysis of video footage generated by the surveillance camera that the accused Abdul Hasan had committed the murder.  Published - December 10, 2024 07:05 pm IST"
  },
  {
    "title": "Four sentenced to life for murdering engineering student",
    "content": "The Principal District and Sessions Court here on Wednesday sentenced four youth to undergo life imprisonment for murdering an engineering student here a few years ago. Principal District Judge S. Kumaraguru also slapped a fine of Rs.3,000 each on S. Rajarajan, A. Armas, R. Sirajudeen and K.S. Vimal alias Vimal Karthik. The student Ajay Ruban, who was 19 years old at the time of murder, was attacked on the night of December 31, 2012 by a group of youth. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Ajay Ruban was a senior student in the same school here where Rajarajan, Armas and A. Ramprasad studied a few years ago. Ajay Ruban, who was pursuing B. Tech course in a private engineering college at Vallam, was speaking to his friends near a theatre under the Cantonment police station limits when he was attacked. According to the prosecution, Rajarajan abused Ajay Ruban and stabbed him with a knife on his neck. Subsequently, Armas, Sirajuddin and Vimal Karthik also carried out the attack. Ajay was immediately rushed by his friends to a private hospital nearby where he succumbed on January 7, 2013. The Cantonment Police booked a case under IPC sections 302 (murder) 323 (voluntarily causing hurt) and 294 (b) (uttering obscene words in a public place). Rajarajan, Armas, Sirajuddin, Vimal Karthik, Ramprasad and Mohamed Salman Khan – who were all 19 years old then – were named as the accused. The charge-sheet was filed in March 2013 in the case with over 40 prosecution witnesses. The trial commenced in the Principal District and Sessions Court in January 2015. In the verdict, the court imposed only fine of Rs.1,000 each on the other two accused Ramprasad and Mohamed Salman Khan under IPC section 323. Ajay Ruban was speaking to his friends near a theatre when he was attacked  Published - August 25, 2016 12:00 am IST"
  },
  {
    "title": "Man, son, grandson arrested for murder",
    "content": "More than a year after a 50-year-old woman was murdered at her house at Edamalaipattipudur here , a special police team has cracked the case by arresting a 68-year-old man, his son, and grandson on Wednesday. The team has also recovered the 10 sovereign gold chain stolen from her by the trio: Congress Marudhai (68), his son Murugesan (45), and grandson M. Parthiban (21). The victim, S.Valarmathi, was murdered in the late hours of December 11, 2013 at her house at Rajiv Gandhi Nagar and besides the gold thali, an ear-stud weighing 12 sovereigns was looted from her. The E.Pudur police registered a murder for gain case on a complaint from the victim’s husband R.Sornam (62), and a special team was constituted by Commissioner of Police Shailesh Kumar Yadav to probe the case. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Based on information, the team interrogated Murugesan of Musiri who confessed to have committed the crime along with his father and son, a police press release said. Congress Marudhai, who was a fortune teller, came to E.Pudur area and kept a watch on Valarmathi’s house. On learning that Valarmathi normally stayed alone, the man hatched a plot along with his son and grandson. The trio came to E. Pudur area, and under the guise of seeking alms, Murugesan and Congress Marudhai entered Valarmathi’s house. Parthiban was asked to wait near the rear side of the house to keep a watch. Upon entering the house, Murugesan and Congress Marudhai tried to rob the ‘thali’ from the woman. As she raised an alarm, the accused pushed her on a cot and smothered her face with a blanket and murdered her. The accused were remanded in judicial custody, the release added.  Published - January 22, 2015 12:00 am IST"
  },
  {
    "title": "BJP Tiruchi unit member murdered",
    "content": "A 38-year-old Bharatiya Janata Party member was murdered by two persons at the busy Gandhi Market area on Monday morning. The victim F. Vijay Raghu of Pensioners Lane in Varaganeri area, was the party’s Palakkarai zonal vice president. He worked in a cycle stand, issuing tokens. He was attacked by the duo with sharp weapons causing grievous injuries. The culprits fled the spot after committing the crime. Mr. Raghu was rushed to Mahatma Gandhi Government Hospital and died while undergoing treatment a couple of hours later, police said. Gandhi Market police are on the look out for ‘Mittai’ Babu and his associate Vijay Sankar, in connection with the murder. Police looked at the closed circuit television footage to establish the identity of the culprits. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. According to police, Vijay Raghu’s daughter and ‘Mittai’ Babu were said to have been in love with each other. ‘Mittai’ Babu had some cases pending against him, including one for allegedly assaulting Vijay Raghu’s brother-in-law earlier, and had come out from the prison only a few days ago. Police said Vijay Raghu apparently did not approve of the love affair. ‘Mittai’ Babu reportedly felt that Vijay Raghu was a stumbling block in the affair. A few hours after the murder, a group of BJP functionaries staged a protest in front of the Mahatma Gandhi Government Hospital demanding the arrest of the accused involved in the killing. Special teams have been formed to apprehend ‘Mittai’ Babu and his accomplice, Vijay Sankar who are on the run.  A team has left for Tiruvarur and another to Perambalur in search of the duo, Commissioner of Police V. Varadharaju told The Hindu . Gandhi Market police are investigating.   Published - January 27, 2020 02:15 pm IST  Tiruchi "
  },
  {
    "title": "Two more arrested in murder case",
    "content": "Two more persons were arrested by the police on Friday in connection with the murder of a history-sheeter S. Muthukumar.  S. Muthukumar, 32, from Thidir Nagar in Ariyamangalam was murdered on April 30 along the Tiruchi-Thanjavur National Highway. On May 1, five persons were arrested by Ariyamangalam police based on a complaint filed by Muthukumar’s mother Kayalvizhi.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. On Friday, M. Mubarak, 32, surrendered before a judicial magistratre. Later, S. Prasad, 24, surrendered at the Ariyamangalam police station. The police transferred both to Pudukottai district prison.  Muthukumar’s murder is suspected to be a sequel to a feud between his father Sekar and his brother Periyasamy. Both Sekar and Periyasamy were murdered by rival groups.   Published - May 03, 2024 08:47 pm IST  Tiruchi / murder "
  },
  {
    "title": "Youth murdered by gang near Jeeyapuram",
    "content": "A 17-year-old youth was murdered by an armed gang at Thindukarai bus stop near Jeeyapuram in the district on Friday. Police gave the name of the victim as G. Mathir Vishnu of Kodiyalam. The victim had a murder case booked against him in Jeeyapuram police station in 2023. Police sources said Mathir Vishnu was travelling on one of the footboards of a government bus. As the vehicle started moving from Thindukarai bus stop, a person is alleged to have dragged him out of the vehicle.  A gang which lay in wait near the spot attacked Mathir Vishnu with sharp weapons and escaped in a two-wheeler. The victim died on the way to hospital. The identity of the killers was yet to be established. The Jeeyapuram police are investigating.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - November 15, 2024 07:27 pm IST"
  },
  {
    "title": "Teenager beaten to death in Srirangam",
    "content": "A youth was beaten to death allegedly by a group of three men at Geethapuram on Friday.  Ranjith Kumar, 18, was beaten to death when he was visiting his extended family at Srirangam. The accused, Naveen Kumar, 23, Vijay, 23, and Suresh, 24, picked a quarrel with Ranjith Kumar when he visited the Cauvery at Geethapuram and allegedly attacked him in an inebriated condition.  The police have arrested the three accused and are investigating.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - August 03, 2024 07:34 pm IST  Tiruchi / murder "
  },
  {
    "title": "Four-member gang kills youth in broad daylight",
    "content": "A 23-year-old man was murdered by a gang of four members in broad daylight at Woraiyur in Tiruchi on Friday.  According to police, there was enmity between the victim Kopparai alias M. Shanmugam, 23, a native of Sannathi Street in Woraiyur, and the suspected accused K. Maris Raja, 45, from a nearby locality. There was a quarrel between them on March 19, during a horse race at Pazhanganagudi near Thiruverumbur.  At this juncture, Shanmugam was murdered using sharp weapons near a tea shop at Woraiyur by a gang of four unidentified persons on Friday afternoon. The Woraiyur police recovered his body and sent it to Mahatma Gandhi Memorial Government Hospital for postmortem.  Police suspect the gang members to be the accomplices of Maris Raja, who was lodged in Tiruchi Central Prison in another case. The police have launched a search for the accused.  Published - May 26, 2023 07:48 pm IST"
  },
  {
    "title": "Tiruchi police crack murder case after two years",
    "content": "A murder case registered in 2021 at Uppiliyapuram was solved with the perpetrator being caught on Saturday.  R. Prabhu, 31, was murdered in November, 2021. With investigation making slow progress, the police recently formed a special team, which detained 20 suspects. During interrogation, one of the suspects, N. Ramesh,29, admitted to the murder stating that he stabbed Prabhu as he failed to return money borrowed from him. He dumped the weapon used to commit the murder in a well along with the victim’s phone and fled the spot.  The police personnel who solved the case would get ₹15,000 as reward from Tiruchi Superintendent of Police V. Varunkumar, the police said.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - June 16, 2024 09:38 pm IST  Tiruchi / murder "
  },
  {
    "title": "Man found murdered at Keezha Devadhanam",
    "content": "A 35-year-old man was found murdered at his house at Keezha Devadhanam in the city on Saturday, September 14, 2024.  According to police sources, Prithiviraj, a DMK functionary, was found in a pool of blood at a room in his house and is believed to have been beaten to death.   Prithiviraj reportedly had an altercation with a person in the morning. Police suspect that the murder could have been a sequel to the incident. Further investigations were on.    Published - September 14, 2024 08:52 pm IST  Tiruchi "
  },
  {
    "title": "Man hacked to death in Tiruchi",
    "content": "An armed duo hacked to death a 24-year-old man at Mela Kalkandarkottai here on Tuesday. The murder was committed in the evening when the victim K. Javid Hussain, a resident of Mela Kalkandarkottai, had just ventured out and was a few metres away from his home. Armed with sharp weapons, the duo attacked Javid Hussain on his face and other parts of the body killing him on the spot, said the police. The killers fled from the crime scene after committing the murder. The motive behind the murder and the identity of the accused are yet to be established. The Ponmalai Police is conducting the probe.   Published - May 07, 2019 11:26 pm IST  Tiruchi "
  },
  {
    "title": "Man gets life imprisonment for killing son in Tiruchi",
    "content": "The Additional District Court - I in Tiruchi on Tuesday convicted and sentenced a 55-year-old man to undergo life imprisonment on the charge of murdering his son, a person with disability. According to police, the murder took place on on December, 22, 2020 at the house of the convicted man, S. Thangavel, at Lakshmanapuram village. He killed his 20-year-old son T. Gopi under the influence of alcohol and hid the body in a septic tank at his house. Based on the complaint from the Village Administrative Officer of Pillapalayam, Thathaiyangarpettai police registered a case. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. After the trial, the Additional District Judge - I pronounced the verdict on Tuesday. Thangavel was convicted and sentenced to undergo life imprisonment under Section 302 (Punishment for murder) and seven years of rigorous imprisonment under Section 201 (causing disappearance of evidence or giving false information to screen offender) of the Indian Penal Code. The sentence would run concurrently.  Published - August 01, 2023 04:40 pm IST"
  },
  {
    "title": "Murder accused shot in the leg in Tiruchi",
    "content": "A history sheeter Jambu alias K. Jambukeswaran, 36, who was arrested in connection with the killing of M. Suresh alias ‘Attukutty’ Suresh in Srirangam on Sunday night, was shot in the leg by a police officer on Monday after he allegedly assaulted a police team when he was taken for recovery of weapons on Monday.  Sub-inspector Rajagopal and Srirangam Inspector Vetrivel, who were injured in the alleged assault by Jambukeswaran, have been admitted to the Mahatma Gandhi Memorial Government Hospital in Tiruchi. Jambukeswaran too has been admitted in the hospital.  The assault took place on Monday evening near Melur in Srirangam when a police team, led by Inspector Vetrivel, took him to a place near Melur in Srirangam for recovery of weapons based on his confession, said the police. Jambukeswaran was arrested earlier in the day.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Jambukeswaran is alleged to have assaulted the team during the recovery forcing Inspector Vetrivel to open fire with his service pistol and shoot on the left leg of Jambukeswaran in “self defence”, said a source.  Jambukeswaran was cited as one of the accused in the killing of ‘Attukutty’ Suresh. Suresh was an accused in the murder of ‘Thalavetti’ Chandru alias Chandramohan - another history sheeter - in Srirangam in 2020. Sunday’s murder of of Suresh is believed to be a revenge killing.  Suresh was riding a two-wheeler with his wife Rahini on the pillion when a gang attacked him at Ambedkar Nagar in Srirangam with swords. Suresh died on the spot. Rahini sustained injuries in the attack by the gang and is undergoing treatment at the Government Hospital in Tiruchi. The body of Suresh was cremated on Monday after completion of autopsy at Srirangam Government Hospital. The Srirangam police registered a murder case on a complaint lodged by Rahini.   Published - September 23, 2024 05:24 pm IST  Tiruchi / murder "
  },
  {
    "title": "Two arrested on murder charge in Tiruchi",
    "content": "The Tiruchi City Police on Monday arrested two persons in connection with the murder of a 27-year-old man near the Ex-servicemen Colony at Ponmalai in the city. The arrested persons were Bhava alias R. Stanley, 27, a native of Ponmalai, and K. Sathish, 23, from Melakalkandarkottai.  According to the police, M. Muthupandi, 27, a native of Vivekananda Nagar in Melakalkandarkottai, who had been working as a mechanic in Coimbatore, was found dead with severe injuries in his body near Puthu Nagamma Temple at the Ex-servicemen Colony near Ponmalai in Tiruchi on December 31.  The Golden Rock police had registered a case and launched an investigation. During the investigation, the police came to know that the accused and the victim had previous enmity. The police arrested the accused persons on Monday and remanded them in judicial custody at Tiruchi Central Prison.   Published - January 02, 2024 06:29 pm IST  Tiruchi / crime "
  },
  {
    "title": "Ramajeyam murder case: Hearing on SIT petition seeking polygraph test on suspects adjourned to November 7",
    "content": "Hearing on the petition filed by the Special Investigation Team (SIT) probing the decade-old murder of K.N. Ramajeyam, brother of Municipal Administration Minister K.N. Nehru, seeking to conduct polygraph tests on 13 suspects was adjourned to November 7 by a Judicial Magistrate court here on Tuesday.  Summons had been issued to the 13 suspects by the Judicial Magistrate Court - VI recently based on the petition filed by the SIT. The Court had directed the 13 suspects to appear before it on Tuesday in order to obtain their consent for undergoing the polygraph tests. Twelve of the suspects were involved in murder cases at various places. One of them was a prisoner lodged in the Central Prison at Cuddalore, who was brought with police escort to be produced at the the Court. SIT officers and the counsels of the suspects were present when the petition came up for hearing on Tuesday morning. The court asked the SIT to file an affidavit and adjourned the hearing to November 7.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. A counsel who appeared for one of the suspects later told reporters outside the court that a Deputy Superintendent of Police of the SIT had filed the petition in the court instead of a Superintendent of Police and he had raised an objection on this. The counsel wondered as to how the SIT had arrived at the list of suspects to conduct the polygraph test.  The Madras High Court had in February this year ordered that a SIT be constituted to conduct probe into the 2012 murder of Ramajeyam at Tiruchi. The High Court had also said that it would monitor the investigation conducted by the SIT headed by Superintendent of Police Jeyakumar. The body of Mr. Ramajeyam, a businessman who had dealt in granite mining and real estate, was found on the banks of Cauvery river near Tiruvalarsolai on the outskirts of Tiruchi on March 29, 2012. The circumstances indicated that he was murdered after being abducted apparently when he went out for a morning walk. The case which was initially investigated by the Tiruchi City police was subsequently transferred to the Crime Branch - CID which was unable to achieve a breakthrough till 2017. Subsequently, the investigation was transferred to the Central Bureau of Investigation (CBI) on an application filed by Latha Ramajeyam, wife of the deceased. However, the CBI too could not achieve any headway in the murder case forcing the family members of Ramajeyam to make another application for the constitution of a SIT. The SIT had conducted enquiries with several persons, including members of the family of Ramajeyam.  Published - November 01, 2022 07:44 pm IST"
  },
  {
    "title": "Armed gang murders history sheeter in Srirangam",
    "content": "A history sheeter was murdered by an armed gang at Srirangam here on Tuesday.  Anbu alias D. Anbarasan, 32, a resident of Srirangam, was returning from a gymnasium on a motorcycle when an armed gang which came in a couple of two-wheelers intercepted him on Teppakula Street near a toilet. Anbarasan took to his heels and was chased by the gang members who attacked him with ‘aruvals’, causing grievous injuries, and fled from the scene. The attack during the morning peak hour in the area shook passers-by. Anbarasan was rushed to Srirangam Government Hospital where he died, said police sources.  The news of the murder of Anbarasan shocked the family members of the victim, who staged a road roko in front of Srirangam government hospital demanding arrest of the killers. They withdrew the protest after the police personnel intervened. Previous enmity is suspected to be behind the killing. A few persons have been detained for questioning in connection with the murder. Srirangam police are investigating the case.  Published - January 28, 2025 07:37 pm IST"
  },
  {
    "title": "Man found murdered near Ponmalai in Tiruchi",
    "content": "A 27-year-old man was found dead near Puthu Nagamma Temple at the Ex-servicemen Colony near Ponmalai in Tiruchi on Sunday evening.  According to police sources, they received an alert from the local people that a man was found dead with severe cuts on his body. The Golden Rock police rushed to the spot and identified the victim as Muthupandi, 27, a mechanic hailing from Melakalkandarkottai.  The police suspect that he was murdered by unidentified persons and launched a search to arrest the accused. The motive behind his murder was yet to be ascertained. His body was shifted to the Mahatma Gandhi Memorial Government Hospital for postmortem.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - December 31, 2023 08:33 pm IST  Tiruchi / murder "
  },
  {
    "title": "Boy murders 21-year-old man for snatching his cell phone",
    "content": " A 21-year-old youth was found murdered in a public toilet in Fort police station limits here on Monday night.  The Fort Police have detained a 16-year-old boy in connection with the murder. Police identified the deceased as Mohamed Ishaq of Tennur area. Police sources said there were cases of pocket picking booked against Ishaq in different police stations in the city limit.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Ishaq allegedly snatched a cell phone belonging to the minor boy near Thillai Nagar a week ago.  The boy’s mother bought him the cell phone. Angered by this, the boy through his friend called the former.  Ishaq and the boy were reportedly consuming liquor inside the toilet when a wordy quarrel broke out between the two.  The boy allegedly attacked Ishaq with a sharp weapon on his neck killing him and left the spot. Police sources said based on information and perusal of CCTV footage in the area the police apprehended the minor boy in connection with the crime.  The boy was later sent to the Government Observation Home here.  The Fort Police have registered a case.   Published - January 29, 2020 05:04 am IST  murder / Tiruchi "
  },
  {
    "title": "Elderly woman murdered by grandson during a spat",
    "content": "A 43-year-old man allegedly murdered his 94-year-old grandmother at Sengattupatti in Thuraiyur taluk in the district in the early hours on Sunday. The Thuraiyur police are on the look out for the accused, P. Muraliraja, and have registered a case against him on a complaint lodged by his mother P. Bhanumathi, 70. The police gave the name of the murdered woman as R. Nagalakshmi. Muraliraja, who had divorced his wife, used to frequently demand money to consume liquor and quarrelled with his mother and grandmother on Saturday late night. He allegedly hit his grandmother with a wrench killing her on the spot.   Published - September 29, 2024 09:43 pm IST  Tiruchi / murder "
  },
  {
    "title": "No breakthrough in Sobanapuram double murder case",
    "content": "Breakthrough eludes investigators probing the double murder of a young couple reported under Uppiliyapuram police station limits in the district last week. Notwithstanding strenuous efforts by special police teams, the accused and their motive remain unknown. The bodies of the couple — T. Rajkumar (27) and R. Saratha (22) — with severe cut injuries on head, neck and hand were found in front of their group house constructed under a government scheme at Sobanapuram. Police sources said eight special teams including some of the best Inspectors were working to achieve a breakthrough in the case at the earliest. The special teams had been probing the case from various angles but were yet to get any tangible clue that could lead them to the accused. The crime spot was an isolated place, said a senior police officer. The teams also could not find any clue from the crime scene, which was visited by fingerprint experts and scientific assistants. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Tiruchi Superintendent of Police Sujit Kumar said he was reviewing the progress made by the special teams daily and expressed hope that the case would be cracked at the earliest. The Uppiliyapuram case is one among the 18 cases of murder reported under Tiruchi Rural Police limits since January. Breakthrough has been achieved in 17 of them. Sudden provocation after a wordy quarrel and previous motive have been cited as reasons in most of the murder cases. Property disputes, family feuds and illegal intimacy have also been cited as other reasons for the murders. The police have categorised the motives behind the murders under different heads, including family dispute, wordy quarrel, drunken brawl, revenge and other reasons. Police statistics reveal that sudden provocation after a wordy quarrel was the reason for five murders. Previous motive led to five other murders. Family dispute was the cause of three murders and three others were committed due to property disputes. Illegal intimacy was cited as the reason in one murder case, police sources said.  Published - July 11, 2023 08:21 pm IST"
  },
  {
    "title": "Four surrender to police in Thottiyam on murder charge",
    "content": "Four persons accused of murdereing a 22-year-old man surrendered before Thottiyam police in Tiruchi district on Sunday. According to police, M. Krishnamurthy, 22, a native of Karuppampalayam and an accused in a murder case registered at Kattuputhur police station, went missing on July 21 when he came to appear before Thottiyam Court. Based on a complaint from his wife K. Gopika, the police registered a missing case. During the investigation, four suspects S. Srinath, P. Karthik, R. Saravanan, and P. Gopalakrishnan confessed to the police that they kidnapped Krishnamurthy and handed him over to a six-member gang. The police arrested the four persons and remanded them. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Meanwhile on Sunday four persons of the six member gang surrendered at Thottiyam police station.  Police sources said M. Ravivarman and M. Hemalatha, brother and mother of complainant Gopika along with N. Dinesh, R. Pappathi took Krishnamurthy in a four-wheeler and murdered him. They threw his dead body in the Cauvery River near Grand Anaicut. The reason behind the murder was said to be a dispute among family members over Gopika’s marriage with Krishnamurthy, who were related as brother and sister, police sources said. The Thottiyam police on Sunday altered the missing case into a murder case and arrested them. Police are also searching for two other absconding persons in the murder.  Published - July 30, 2023 11:54 pm IST"
  },
  {
    "title": "Ramalingam murder case: 11 in NIA custody",
    "content": "The National Investigation Agency (NIA), probing the murder of Pattali Makkal Katchi functionary Ramalingam of Tirubuvanam near Kumbakonam in Thanjavur district in February, has taken into custody the 11 accused arrested in connection with the killing.  The NIA filed a petition in a Special Court at Poonamalee in Chennai on Monday seeking custody of the accused. Police sources said the court allowed the NIA custody of the accused till June 3. The accused were brought to Thanjavur amid heavy police escort on Monday night.  The 11 accused include Mohamed Riaz, Mohamed Hassan Kuthoos, Mohamed Farooq, Mohamed Rizwan, Mohamed Taufiq, Mohamed Ibrahim, Tauhid Basha and Nizam Ali. The case was initially investigated by Thiruvidaimarudur police.  As part of its investigation, NIA split into teams and conducted simultaneous searches at the offices of the Popular Front of India in Tiruchi, Thanjavur and Karaikal and seized hard discs, memory cards, CDs and DVDs, besides mobile phones, early this month.   Published - May 28, 2019 10:12 pm IST  Tiruchi "
  },
  {
    "title": "Woman murdered",
    "content": "Seventy-five-year old Nagalakshmi was found murdered at her residence in BHEL township on Thursday. Intruders had reportedly decamped with 25 sovereigns gold jewellery and Rs.7,000 cash after committing the murder. The aged woman, whose husband Srinivasan had expired recently, was alone after her son, Nagaraj, a BHEL employee, and daughter-in-law, Ezhilmathi, a school teacher in the township, had gone for work.When Nagaraj went home for lunch, he found the door locked from outside. Presuming that his mother would have gone to the hospital he went there, and subsequently to the school where he collected the key from his wife. On opening the house, Nagaraj found his mother dead with strangulation marks. The Deputy Inspector of Police A. Amalraj and Supterintendent of Police Lalitha Lakshmi visited the spot.  Published - July 08, 2011 10:34 am IST  Tiruchi "
  },
  {
    "title": "NIA conducts searches at 15 locations in PMK functionary murder case",
    "content": "The National Investigation Agency (NIA) on Thursday conducted simultaneous searches on the premises of persons suspected to be associated with five absconding offenders in the PMK functionary V. Ramalingam murder case in Tiruchi, Thanjavur, Tiruvarur, Nagapattinam, Mayiladuthurai, and Karaikal districts.  Carried out by multiple teams of the NIA, which is probing the case, the searches at 15 locations led to the seizure of digital devices and documents connected to the case. Ramalingam was murdered on February 5, 2019, at Paku Vinayakam Thoppu in Thanjavur, allegedly by members and office-bearers of the Popular Front of India (PFI).  The accused conspired to kill Ramalingam as he had intervened in the forcible conversion of the underprivileged persons by a PFI team of Arivagam in Theni.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The investigation established that the violence was unleashed to strike fear among those who opposed the PFI, the NIA said in a release. The PFI has been declared an unlawful association under the Unlawful Activities (Prevention) Act by the Central government in September 2022.  The NIA had filed a charge sheet against 18 accused persons, including the five absconding persons, in August 2019 before the NIA Special Court in Chennai. The court declared the five absconding accused — Mohammed Ali Jinnah, Abdul Majith, Bhurkanudeen, Shahul Hameed, and Nafeel Hasan — as proclaimed offenders. The NIA has announced a reward of ₹5 lakh for information leading to their arrest, the release added.  Published - August 01, 2024 07:26 pm IST"
  },
  {
    "title": "Man murdered",
    "content": "A man from Thiruvanaikoil, who was critically injured after being attacked with knife by a duo on Friday, died on Saturday.  S. Narayanan, 58, a painter from Manalmedu in Thiruvanaikoil had given money to R. Krishna Kumar of Othatheru to buy him liquor. But, he and Sony of the same area, who were in a liquor shop on Friday, reportedly refused to budge, which led to a verbal exchange. It escalated into a clash. Krishna Kumar and Sony attacked Narayanan with knife. He was rushed to Tiruchi Government Hospital. But he died on Saturday. Srirangam police have registered a murder case against Krishna Kumar and Sony  Published - September 07, 2019 10:19 pm IST"
  },
  {
    "title": "TVK general secretary pays homage to accident victims",
    "content": "Tamilaga Vettri Kazhagam (TVK) General Secretary N. Anand on Monday paid his last respects to party office-bearers V.L. Srinivasan, 35, and Woraiyur Kalai alias Kalaikovan, 40, who died in a road accident near Sheik Hussainpet in Ulundurpet, Kallakurichi district, while travelling to attend the party’s conference in Vikravandi on Sunday . Srinivasan was the president of Tiruchi South district youth wing of the party while Kalai was the vice president.  Srinivasan, a resident of Big Kammala Street in Tiruchi, leaves behind two sons while Kalaikovan, who lived with his parents in Woraiyur, was unmarried. During his visit, Mr. Anand extended condolences to the families and assured them of the party’s commitment to support them.  “It is a huge loss and the TVK will take care of their families,” Mr. Anand told reporters. Answering questions and criticisms on the absence of a formal condolence from TVK leader Vijay so far, he added: “He was the one who asked me to visit these families. A condolence statement will be issued soon.”   Published - October 28, 2024 08:34 pm IST  Tiruchi / politics / Tamilaga Vettri Kazhagam "
  },
  {
    "title": "20-year-old woman murdered by husband",
    "content": " A 20-year-old woman was murdered allegedly her husband in their house at Kuzhumani on the city’s outskirts in the early hours on Sunday. The accused M. Chozhan (21) involved in centring works surrendered at the Jeeyapuram police station after committing the murder, said the police. The couple have a six-month-old male child. Police said family problem between the couple eventually led to the murder of C. Suganya, a native of Kumarapalayam in Namakkal district. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. The sources said Chozhan loved Suganya and married her one-and-half years ago. The woman went to her parent’s house for delivery. Police said Chozhan reportedly did not evince interest in living with his wife thereafter. The woman’s mother Maheswari lodged a complaint to the All Women Police Station at Jeeyapuram against Chozhan on Saturday. The police held talks with both parties and Suganya thereafter left for Chozhan’s house at Kuzhumani. Police said Suganya was fast asleep in the house when Chozhan threw a grinding stone on her head killing her.  He surrendered to the Jeeyapuram police station thereafter. The Jeeyapuram police arrested Chozhan and registered a case of murder.  Published - December 18, 2017 08:13 am IST"
  },
  {
    "title": "Man murders wife near Lalgudi",
    "content": "A 32-year-old man allegedly killed his wife in their house at Natarajapuram near Lalgudi in the district in the late hours on Monday. The police gave the name of the deceased as Anusuya, 27. The Lalgudi police are on the look out for the victim’s husband Rajesh who was an astrologer.  The police said Rajesh was addicted to alcohol. The couple had a tiff on Monday night and in a fit of rage, Rajesh allegedly attacked his wife with a sword and hit her on the head killing her on the spot. The Lalgudi police have registered a case.   Published - October 01, 2024 06:48 pm IST  Tiruchi / murder "
  },
  {
    "title": "Three arrested on murder charge in Manapparai",
    "content": "The Tiruchi district rural police on Sunday altered a woman missing case into a case of murder and arrested three persons.  Police sources said J. Kamalaveni, 65, a money lender and native of Eda Street in Manapparai, went missing on August 16. Based on a complaint from her daughter, G. Malarvizhi, the Manapparai police registered a missing case. During the investigation, the police found a scuffle broke out between Kamalaveni and her neighbour R. Saraswathi on August 16, in which the money lender was pushed down by the latter. She suffered severe injuries and died on the spot. Later, along with her son R. Harshan, 19, and daughter R. Varshini, 23, Saraswathi dumped Kamalaveni’s body in a well. The police recovered the body from the well and arrested the trio. The case was altered from woman missing to 302 (Punishment for murder) and 201 (Causing disappearance of evidence of offence, or giving false information to screen offender) of the Indian Penal Code.   Published - September 04, 2023 07:39 pm IST"
  },
  {
    "title": "Duo held for killing three persons",
    "content": "More than a year after a couple were murdered at Perakambi village near Siruganur in the district, a special police team cracked the double murder case and arrested two youth on Tuesday on charge of committing the crime. The accused, S. Kishanth, 21, of Chathiramani in Perambalur district, and K. Palanisamy, 21, of Valaiyur near Manachanallur in Tiruchi district, also allegedly confessed to killing 18-year-old K. Perumal with a boulder in 2017. Perumal was the brother of Palanisamy. A police press release said the couple, A. Ramesh, 37, and R. Latha, 38, were asleep in front of their house on April 23, 2018, when they were attacked with deadly weapons by the men. The woman died on the spot, while Ramesh succumbed to injuries later at hospital. Further, a motorcycle at the spot was found stolen. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Acting on a complaint preferred by Ramesh’s brother Rajkumar, Siruganur police registered a case of murder and launched investigation. A special team was constituted on the instruction of Superintendent of Police, Tiruchi, Ziaul Haque to probe the case and arrest the killers.  During investigation, it came to light that the registration plate of the stolen motorcycle had been changed to Tamil and was involved in an accident case in Veppur police station in Cuddalore district. Based on the lead, the special team tried to find the owner of the vehicle and the rider. During investigation it was established that it was the same motorcycle that was reported stolen in the double murder case and two men, S. Kishanth and P. Manikandan, were the riders.  It came to light that Kishanth and his friend Palanisamy murdered the couple and stole the motorcycle, ₹3,000 cash and a gold ring and chain worn by Ramesh. Kishanth and Palanisamy allegedly confessed to killing the couple.  The two also confessed to have murdered Perumal in a forest area between Devimangalam and Maniyakurichi in December 2017 due to previous enmity.  The duo were arrested in both cases and produced before the Lalgudi Judicial Magistrate court and sent for remand, the release added.   Published - February 25, 2020 06:39 pm IST"
  },
  {
    "title": "Life term for three in murder case",
    "content": "The III Additional District Judge here on Wednesday convicted and sentenced three persons to undergo life imprisonment for murdering M. Shahul Hameed, 40, in March 2009.  Those convicted were Feroz Ahamed, Pandikumar and Francis Prabhu. The case was probed by the Crime Branch CID after it was transferred to it for investigation.  Shahul Hameed, who was a resident of Dhanarathina Nagar here, was reported missing from March 1, 2009. He was last seen in association with a local rowdy, John Nepolian. Initially, the Gandhi Market police registered a case. Since whereabouts of Shahul Hameed was not known, his wife Jawahar Nisha filed a habeas corpus petition in the High Court and pleaded that the case be transferred to the CB-CID.  This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. Subsequently, the case was transferred to the CB-CID, Tiruchi unit, to take up investigation. The CB-CID arrested Umar Farook, Feroz Ahamed, Pandikumar and Francis Prabhu on the charge of murdering Shahul Hameed. The murder was committed due to money transaction. In the meantime, Umar Farook died.  The trial was held and the verdict was pronounced by the III Additional District Judge who slapped fine of ₹ 1,000 on the three convicted persons.  Published - January 22, 2020 09:35 pm IST"
  },
  {
    "title": "Man sentenced to life imprisonment for murder in Tiruchi",
    "content": "The Mahila Court in Tiruchi on Tuesday convicted and sentenced a 49-year-old man to undergo life imprisonment on murder charge. The judgement was pronounced in a case registered at Somarasampettai police station in April 2018. Special Public Prosecutor M.K. Zakir Hussain said the accused, K. Kamaraj of Somarasampettai was arrested for murdering his wife K. Ilavarasi over a dowry dispute and remanded in judicial custody. The Tiruchi Mahila Court Sessions Judge N.S. Srivathsan, who heard the case, convicted Kamaraj and sentenced him to undergo life imprisonment. The court also imposed a fine of ₹15,000 on him and recommended to the District Collector to pay a compensation of ₹1 lakh each to the two minor children of the victim, the prosecution added. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window.  Published - September 05, 2023 07:52 pm IST"
  },
  {
    "title": "SC youth murdered in clash with caste Hindu group; eight detained",
    "content": "A 24-year-old Scheduled Caste youth, J. Nepoliyan, was killed in a clash between groups of caste Hindus and SC people at Thiruvalarsolai in Tiruchi on Sunday. The clash was reported to be a sequel to a quarrel between the two groups at Agalanganallur near Lalgudi on Saturday, when P. Nagendran, 24, from the caste Hindu community had told a female college student from same community that he wished to marry her. He was accompanied by his friend M. Jeevanantham, 34, of the Scheduled Caste, on the day. Irked over Nagendran proposing to the girl, a group of caste Hindus had picked a quarrel with the duo and they had reportedly come to blows. This is a modal window. Beginning of dialog window. Escape will cancel and close the window. End of dialog window. On Sunday evening, tension escalated into a clash between the caste Hindus and the SC people near Thiruvalarsolai under Srirangam police limits when K. Vignesh and 12 others from the caste Hindu community allegedly attacked six SC people, including Nepoliyan. Seven persons were injured in the clash. A severely injured Nepoliyan died on way to hospital. Four SC people and a caste Hindu man were referred to Srirangam Government Hospital for treatment. Srirangam police have detained eight persons in connection with the case booked under various sections of the Bharatiya Nyaya Sanhita and the Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, and are conducting further investigations.  Published - July 08, 2024 09:33 pm IST"
  }
]
    